version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: chat-postgres
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: StrongPassword123
      POSTGRES_DB: chat_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
